In [1]:
import pandas as pd

df = pd.read_csv("csv_files/outputs_classified_bucket_with_embeddings.csv")

df.head()

,image_id,predicted_type,embedding
0,00bcce0f.jpg,nature,"[0.013632039539515972, 0.011957136914134026, -..."
1,01146212.jpg,nature,"[0.02265600673854351, 0.024179676547646523, -0..."
2,018b51ef.jpg,nature,"[-0.006416882388293743, 0.002040758728981018, ..."
3,02.jpg,nature,"[-0.0062610129825770855, 0.00975512433797121, ..."
4,025f1dd8.jpg,nature,"[0.02386866882443428, 0.015808453783392906, 0...."

In [2]:
len(df)

20888

In [4]:
df.predicted_type.info()

<class 'pandas.core.series.Series'>
RangeIndex: 20888 entries, 0 to 20887
Series name: predicted_type
Non-Null Count  Dtype
--------------  -----
20888 non-null  object
dtypes: object(1)
memory usage: 163.3+ KB

In [5]:
df.tail()

,image_id,predicted_type,embedding
20883,xfv4Ek6qRre3Ud7p9row_sylwiabartyzel_unsplash_0...,nature,"[-0.037626322358846664, 0.001448533614166081, ..."
20884,xpdPwXTASnOUXFpIPgDs_IMG_1460_edt.jpg,nature,"[0.03617142140865326, 0.03307915851473808, 0.0..."
20885,xzuvhgdQGul0amA3Qc7a_373A9681.jpg,nature,"[-0.03340290114283562, 0.04066048562526703, 0...."
20886,yUjdwp7gT7HirqscXb35_DSC_8744.jpg,nature,"[0.017090287059545517, 0.00037826262996532023,..."
20887,yZfr4jmxQyuaE132MWZm_stagnes.jpg,nature,"[0.012660587206482887, 0.03728405386209488, -0..."

In [6]:
df.predicted_type.value_counts()

predicted_type
nature    18363
city       2525
Name: count, dtype: int64

In [7]:
df.embedding.isna().sum()

0

In [8]:
df.image_id.nunique()

20888